### ISSUE TITLE
OK Viz Sparkline

### ISSUE THREAD

**Issue by adriantheuma** [okviz/Sparkline#11]
Hi, 

I downloaded and used the visual successfully. This is more a suggestion for an enhancement rather than an issue:

1. It would be good if you can click on the category and other visuals on the page are updated to highlight data for that category. At the moment that it seems that this only works when you select a particular point on the chart.

2. Also the ability to align the x and y axis so that values can be compared across categories (similar to the align axis in SSRS)

3. Potentially an issue - when dragging a date in the Axis and choose to show the hierarchy the date is only expanded to the year level (omitting quarter, month and day)

Thank you, 

Adrian

**Comment by danieleperilli** [comment]
Thanks for your suggestion, we will consider them in a future version.
