### ISSUE TITLE
Size of "points"

### ISSUE THREAD

**Issue by svenvu** [okviz/Sparkline#13]
Hi

As sparklines are intended to be small charts I found that it would be really useful if we could adjust the size of the datapoints so they don't pop out as much on small sparklines.

It would also be more pleasureable for the eyes, especially when more sparklines are used next or below eachother.

Would you consider making this option available so we can change the size of the points to size "1", "2", "3",...

Friendly greets

**Comment by danieleperilli** [comment]
Yes, we certainly include it in the next release.
