### ISSUE TITLE
Color for current point

### ISSUE THREAD

**Issue by svenvu** [okviz/Sparkline#14]
Hi

I would really like to highlight the point for the current selection. I see this option is available but it won't work in the way I am using the sparklines. But really, this would be heaven if this worked.

What I think would be awesome is that I could add a field for the "current selection" so the sparkline can look which value is selected. For example if I add the field "quarter" and also use that field as a slicer/filter, the sparkline knows which quarter(s) is/are selected and can change the color of the points on the sparkline.

Your opinion on this feature is much appreciated!

Friendly greets

**Comment by danieleperilli** [comment]
Sorry, your request is not very clear for me. Can you explain it better?

**Comment by danieleperilli** [comment]
Yes, now I understand. Sorry, we add new features according to user requests. No one requested this before and, frankly I'm not sure it is in line with the purpose of the visual.

**Comment by svenvu** [comment]
Hi @danieleperilli 

Thank you for your feedback!
Ofcourse, someone has to be the first innovator :D and I was aiming my hopes on the sparkline chart but I certainly understand that this is a rather exotic feature I am asking for.

Friendly greets
