### ISSUE TITLE
No Support in PBI October 2017 Version

### ISSUE THREAD

**Issue by pallox** [okviz/Sparkline#16]
On the attempt in using the visual in a Power BI report, I get following message:
`Your version of Power BI Desktop does not support this custom visual. Please update Power BI Desktop to the latest version`
Is it possible to optimise the Sparklines visual for the on-prem version of PBI of October 2017?
Unfortunately this problem persists through all versions available of the Sparkline visual.
![Not supported](https://abload.de/img/cvnotsupported2ud5k.png)
Thank you! Every help is appreciated as my customer also needs a statement on this issue.
Regards,
pallox

**Comment by danieleperilli** [comment]
No, sorry. The visual uses the latest API, not supported by previous versions of Power BI. You can download an old version of the visual from okviz website. You have to choose the BETA version  and it will not be updated automatically. Moreover, it could contains bugs...

**Comment by pallox** [comment]
Thank you, totally oversaw those beta-versions!
