### ISSUE TITLE
(#9220) Decimal places don't work for Value Label

### ISSUE THREAD

**Issue by tomsoir** [okviz/Sparkline#2]
Description: Decimal places don't work for Value Label.
Repro:
1. Launch PowerBI Desktop
2. Open the Gallery Sample
3. Select the 1st visual
4. Go to Format pane > Value Label > Set Display value as Average value
5. Input any value into Decimal places text field

Expected behavior: Visual respects decimal places value
Actual behavior: Visual does not change any displayed values
![2](https://cloud.githubusercontent.com/assets/301881/18556075/e2d13e0a-7b72-11e6-9ad4-949a7caf5ea8.png)

**Comment by danieleperilli** [comment]
The formatting functions are not yet available on the current API.
