### ISSUE TITLE
Sparkline expected operation is not consistent with standard PBI visuals

### ISSUE THREAD

**Issue by bellzz** [okviz/Sparkline#20]
One would expect that clicking a category item in the sparkline visual would cross filter other visuals on the report page. It does not. See attached pbix

[SparklineIssue.zip](https://github.com/okviz/Sparkline/files/2466003/SparklineIssue.zip)

**Comment by danieleperilli** [comment]
Sorry, it doesn't work this way. It is not a bug. Anyway, we will consider it in a future update.
