### ISSUE TITLE
Treat null as zero?

### ISSUE THREAD

**Issue by MobyusMark** [okviz/Sparkline#22]
I love the sparkline viz. Thanks! There may be another way to do this, but I have a visual that represents instances % of total each week of various categories. When there are none, the viz puts a gap in because there isn't any data (I get it - it is logical.) See the attached screengrab. Just wondering how to have a zero instead of a gap. I guess this is a feature request - can the viz have that as an option?

![image](https://user-images.githubusercontent.com/3012329/54238813-d7ce3a00-44ef-11e9-98c5-b11ca8de79b6.png)

**Comment by danieleperilli** [comment]
Yes, you can choose the behavior with blank data points. There is an option in the formatting pane.

<img width="166" alt="Development_-_CardWithStates_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/54255944-5d86cf80-455a-11e9-962a-21fd33e5608c.png">

**Comment by MobyusMark** [comment]
Eesh... yes, should've found that. This is pretty slick. Thanks!
