### ISSUE TITLE
Recommendations for Sparkline

### ISSUE THREAD

**Issue by fordmaxson** [okviz/Sparkline#8]
I am playing around with the new Sparkline component and love the possibilities.  Nice stuff!  Have a couple comments/requests that would allow me to really use it for my audience.

1. Axis labels. pic... 
![image](https://user-images.githubusercontent.com/38134430/38703795-3b29bfc8-3e72-11e8-95d5-12658b604f14.png)

2.  Min chart height. pic... 
![image](https://user-images.githubusercontent.com/38134430/38703790-333dcbe2-3e72-11e8-9260-3074ecbd72e5.png)

Thanks!

**Comment by danieleperilli** [comment]
About the axis: sorry, we don't have any plan to add axis.
About min height: the option already exists, but its name is misleading (we wanted to be coherent with built-in visuals - probably we  will change it on the next update): **Minimum category width** inside **Line** section.
