### ISSUE TITLE
No minimum line height, doesn't work with many items

### ISSUE THREAD

**Issue by andrewtuplin** [okviz/Sparkline#9]
When you have a report with anything other than a tiny amount of data, this viz stops working because the line height becomes very small and all of the lines look flat.  A big improvement would be to allow the user to set the minimum row height so that when there are many items (e.g. > 20) the viz still conveys some information.

**Comment by danieleperilli** [comment]
The option is already there, but has a confusing name (that we changed in the last not yet released update).
![sparkline-heigh](https://user-images.githubusercontent.com/9072177/39800914-c2fa6ec8-5369-11e8-9b79-81d0aed9607f.jpg)
